# Generated by Django 3.0.8 on 2020-08-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200829_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFriending',
            new_name='UserFriends',
        ),
    ]
