# Generated by Django 3.0.8 on 2020-08-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200829_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFriends',
            new_name='UserFriend',
        ),
    ]
