# Generated by Django 3.0.8 on 2020-08-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200829_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFriend',
        ),
    ]
