# Generated by Django 3.0.8 on 2020-08-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_delete_userfriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('friending_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friending', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_friended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('user_id', 'friending_user_id'), name='unique_friending'),
        ),
    ]
